apiVersion: v2
name: bitwarden_rs
description: Unofficial Bitwarden compatible server written in Rust
type: application
version: 0.1.1
appVersion: 1.16.3
keywords:
  - bitwarden
  - bitwarden_rs
  - password
  - rust
home: https://charts.itscontained.io
sources:
  - https://github.com/dani-garcia/bitwarden_rs
maintainers:
  - name: Nicholas St. Germain
    email: nick@cajun.pro
icon: https://raw.githubusercontent.com/bitwarden/brand/master/icons/256x256.png