apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "arr.fullname" . }}
  labels:
  {{- include "arr.labels" . | nindent 4 }}
{{- if .Values.env }}
data:
  {{- toYaml .Values.env | nindent 2 }}
{{- end }}