apiVersion: v1
kind: Service
metadata:
  name: {{ template "arr.fullname" . }}
  labels:
  {{- include "arr.labels" . | nindent 4 }}
  {{- if .Values.service.labels }}
  {{ toYaml .Values.service.labels | indent 4 }}
  {{- end }}
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ template "arr.portSelector" . }}
      protocol: TCP
      targetPort: http
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  {{- toYaml .Values.service.additionalSpec | indent 2 }}
  selector:
  {{- include "arr.selectorLabels" . | nindent 4 }}