apiVersion: v2
name: radarr
description: Radarr Chart
type: application
version: 1.0.1
appVersion: 3.0.0.3591
keywords:
  - radarr
home: https://github.com/k8s-at-home/charts/tree/master/charts/media-common/radarr
sources:
  - https://github.com/Radarr/Radarr
  - https://hub.docker.com/r/itscontained/radarr
maintainers:
  - name: DirtyCajunRice
    email: nick@cajun.pro
dependencies:
  - name: media-common
    repository: https://charts.itscontained.io
    version: 1.0.1
    alias: radarr