apiVersion: v2
name: tautulli
description: Tautulli Chart
type: application
version: 1.0.1
appVersion: v2.5.4
keywords:
  - tautulli
home: https://github.com/k8s-at-home/charts/tree/master/charts/media-common/tautulli
sources:
  - https://github.com/Tautulli/Tautulli
  - https://hub.docker.com/r/tautulli/tautulli
maintainers:
  - name: DirtyCajunRice
    email: nick@cajun.pro
dependencies:
  - name: media-common
    repository: https://charts.itscontained.io
    version: 1.0.1
    alias: tautulli