apiVersion: v2
name: Ombi
description: Ombi Chart
type: application
version: 1.0.0
appVersion: 4.0.471
keywords:
  - ombi
home: https://github.com/k8s-at-home/charts/tree/master/charts/media-common/ombi
sources:
  - https://github.com/tidusjar/Ombi
  - https://hub.docker.com/r/itscontained/ombi
maintainers:
  - name: DirtyCajunRice
    email: nick@cajun.pro
dependencies:
  - name: media-common
    repository: https://charts.itscontained.io
    version: 1.0.0
    alias: ombi