apiVersion: v2
name: traefik-forward-auth
description: A minimal forward authentication service that provides OAuth/SSO login and authentication for the traefik reverse proxy/load balancer
type: application
version: 0.1.0
appVersion: 2.2.0
keywords:
  - traefik
  - traefik-forward-auth
  - oauth
  - oauth2
  - oidc
home: https://charts.itscontained.io
sources:
  - https://github.com/thomseddon/traefik-forward-auth
maintainers:
  - name: Nicholas St. Germain
    email: nick@cajun.pro