#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- See list of available images [here](https://github.com/JetBrains/projector-docker)
  registry: ghcr.io/k8s-at-home
  repository: projector-pycharm-c
  pullPolicy: IfNotPresent
  tag: 2021.1

strategy:
  type: Recreate

# See more environment variables in the projector-docker documentation
# https://github.com/JetBrains/projector-docker
env: {}
  # ORG_JETBRAINS_PROJECTOR_SERVER_HANDSHAKE_TOKEN: "admin-password"
  # ORG_JETBRAINS_PROJECTOR_SERVER_RO_HANDSHAKE_TOKEN: "read-only-password"

# All default config paths will be /config/*
# example: idea.system.path=/config/system
idea: {}
#  config:
#    path: "/data/config"
#  system:
#    path: "/data/system"
#  plugins:
#    path: "/data/plugins"
#  log:
#    path: "/data/log"

sslGen:
  enabled: false
  certs:
    secret: "domain-com-certs"
    crt: "tls.crt"
    key: "tls.key"
  jks:
    dest: "/tmp/cert.jks"
  properties:
    existingSecret: ""
    key: "ssl.properties"

service:
  port:
    port: 8887

ingress:
  enabled: false

persistence:
  config:
    enabled: false
    emptyDir:
      enabled: false
    mountPath: /config
