apiVersion: v2
name: lidarr
description: Lidarr Chart
type: application
version: 1.0.2
appVersion: 0.7.1.1785
keywords:
  - lidarr
home: https://github.com/k8s-at-home/charts/tree/master/charts/media-common/lidarr
sources:
  - https://github.com/Lidarr/Lidarr
  - https://hub.docker.com/r/itscontained/lidarr
maintainers:
  - name: DirtyCajunRice
    email: nick@cajun.pro
dependencies:
  - name: media-common
    repository: https://charts.itscontained.io
    version: 1.0.2
    alias: lidarr